server.port: 8081
spring:
  #数据库配置
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:oracle:thin:@20.26.11.9:1521:CSIBM02
    username: aiam
    password: aiam_123
  redis:
    cluster:
      nodes: 192.168.23.134:7001,192.168.23.134:7001,192.168.23.134:7002,192.168.23.134:7003,192.168.23.134:7004,192.168.23.134:7005,192.168.23.134:7006
    database: 0
    password: redis
    rool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout:  5000ms
#mybatis配置
mybatis-plus:
# mapper-locations: classpath:/mapper/*.xml
# type-aliases-package: com.example.mybatis.entity.*.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: oracle
    refresh: false
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      jdbc-type-for-null: 'null'